/* Simple Plugin API
 * Copyright (C) 2016 Wim Taymans <wim.taymans@gmail.com>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

#ifndef __SPA_AUDIO_LAYOUT_H__
#define __SPA_AUDIO_LAYOUT_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <endian.h>

#define SPA_AUDIO_LAYOUT_Mono		1, SPA_AUDIO_CHANNEL_MONO
#define SPA_AUDIO_LAYOUT_Stereo		2, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR
#define SPA_AUDIO_LAYOUT_Quad		4, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR
#define SPA_AUDIO_LAYOUT_Pentagonal	5, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR, \
					   SPA_AUDIO_CHANNEL_FC
#define SPA_AUDIO_LAYOUT_Hexagonal	6, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_RC
#define SPA_AUDIO_LAYOUT_Octagonal	8, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_RC, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR,
#define SPA_AUDIO_LAYOUT_Cube		8, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR, \
					   SPA_AUDIO_CHANNEL_TFL, SPA_AUDIO_CHANNEL_TFR, \
					   SPA_AUDIO_CHANNEL_TRL, SPA_AUDIO_CHANNEL_TRR,


#define SPA_AUDIO_LAYOUT_MPEG_1_0	SPA_AUDIO_LAYOUT_MONO
#define SPA_AUDIO_LAYOUT_MPEG_2_0	SPA_AUDIO_LAYOUT_STEREO
#define SPA_AUDIO_LAYOUT_MPEG_3_0A	3, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC
#define SPA_AUDIO_LAYOUT_MPEG_3_0B	3, SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_FL, \
					   SPA_AUDIO_CHANNEL_FR
#define SPA_AUDIO_LAYOUT_MPEG_4_0A	4, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_RC
#define SPA_AUDIO_LAYOUT_MPEG_4_0B	4, SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_FL, \
					   SPA_AUDIO_CHANNEL_FR, SPA_AUDIO_CHANNEL_RC
#define SPA_AUDIO_LAYOUT_MPEG_5_0A	5, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_MPEG_5_0B	5, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR, \
					   SPA_AUDIO_CHANNEL_FC
#define SPA_AUDIO_LAYOUT_MPEG_5_0C	5, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FC, \
					   SPA_AUDIO_CHANNEL_FR, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_MPEG_5_0D	5, SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_FL, \
					   SPA_AUDIO_CHANNEL_FR, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_MPEG_5_1A	6, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_MPEG_5_1B	6, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE
#define SPA_AUDIO_LAYOUT_MPEG_5_1C	6, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FC, \
					   SPA_AUDIO_CHANNEL_FR, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR, SPA_AUDIO_CHANNEL_LFE
#define SPA_AUDIO_LAYOUT_MPEG_5_1D	6, SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_FL, \
					   SPA_AUDIO_CHANNEL_FR, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR, SPA_AUDIO_CHANNEL_LFE
#define SPA_AUDIO_LAYOUT_MPEG_6_1A	7, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR, \
					   SPA_AUDIO_CHANNEL_RC
#define SPA_AUDIO_LAYOUT_MPEG_7_1A	8, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_MPEG_7_1B	8, SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR, SPA_AUDIO_CHANNEL_FL, \
					   SPA_AUDIO_CHANNEL_FR, SPA_AUDIO_CHANNEL_RL, \
					   SPA_AUDIO_CHANNEL_RR, SPA_AUDIO_CHANNEL_LFE
#define SPA_AUDIO_LAYOUT_MPEG_7_1C	8, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR


#define SPA_AUDIO_LAYOUT_2_1		3, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_LFE

#define SPA_AUDIO_LAYOUT_2RC		3, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_RC
#define SPA_AUDIO_LAYOUT_2FC		3, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC

#define SPA_AUDIO_LAYOUT_3_1		4, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE
#define SPA_AUDIO_LAYOUT_4_0		4, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_RC
#define SPA_AUDIO_LAYOUT_2_2		4, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR

#define SPA_AUDIO_LAYOUT_4_1		5, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_RC
#define SPA_AUDIO_LAYOUT_5_0		5, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_5_0R		5, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_RL, \
					   SPA_AUDIO_CHANNEL_RR
#define SPA_AUDIO_LAYOUT_5_1		6, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_5_1R		6, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR
#define SPA_AUDIO_LAYOUT_6_0		6, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_RC, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_6_0F		6, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FLC, SPA_AUDIO_CHANNEL_FRC, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_6_1		7, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_RC, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_6_1F		7, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR, \
					   SPA_AUDIO_CHANNEL_RC
#define SPA_AUDIO_LAYOUT_7_0		7, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_RL, \
					   SPA_AUDIO_CHANNEL_RR, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_7_0F		7, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_FLC, \
					   SPA_AUDIO_CHANNEL_FRC, SPA_AUDIO_CHANNEL_SL, \
					   SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_7_1		8, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_7_1W		8, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_FLC, SPA_AUDIO_CHANNEL_FRC, \
					   SPA_AUDIO_CHANNEL_SL, SPA_AUDIO_CHANNEL_SR
#define SPA_AUDIO_LAYOUT_7_1WR		8, SPA_AUDIO_CHANNEL_FL, SPA_AUDIO_CHANNEL_FR, \
					   SPA_AUDIO_CHANNEL_FC, SPA_AUDIO_CHANNEL_LFE, \
					   SPA_AUDIO_CHANNEL_RL, SPA_AUDIO_CHANNEL_RR, \
					   SPA_AUDIO_CHANNEL_FLC, SPA_AUDIO_CHANNEL_FRC

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif /* __SPA_AUDIO_LAYOUT_H__ */
