task:
  freebsd_instance:
    matrix:
      - image_family: freebsd-13-0-snap
  env:
    # /usr/ports/Mk/Uses/localbase.mk localbase:ldflags
    LOCALBASE: /usr/local
    CFLAGS: -isystem $LOCALBASE/include
    CPPFLAGS: $CFLAGS
    CXXFLAGS: $CFLAGS
    LDFLAGS: -L$LOCALBASE/lib
  deps_script:
    - sed -i.bak -e 's/quarterly/latest/' /etc/pkg/FreeBSD.conf
    - pkg install -y meson pkgconf git-lite dbus glib libepoll-shim libudev-devd vulkan-loader vulkan-headers v4l_compat gstreamer1 gstreamer1-plugins libinotify gettext libsndfile sdl2 alsa-lib
    - sysrc dbus_enable=YES
    - service dbus restart
  build_script:
    - mkdir build
    - cd build
    - meson setup -Dalsa=enabled -Draop=enabled -Dv4l2=enabled -Dpipewire-alsa=enabled -Dbluez5=disabled -Djack=disabled -Dpipewire-jack=disabled -Dpw-cat=enabled -Dpipewire-v4l2=disabled -Dsdl2=enabled -Dsystemd=disabled -Dsession-managers=media-session ..
    - ninja
  test_script:
    - cd build
    - ninja test
