sudo: required
language: minimal
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
before_install:
  - docker pull gkiagia/pipewire_build_environment:latest
script:
  - >
    docker run -it --rm -v $PWD:/workdir gkiagia/pipewire_build_environment:latest bash -c
    'cd /workdir && ./autogen.sh \
      -Ddocs=true \
      -Daudiomixer=true \
      -Daudiotestsrc=true \
      -Dffmpeg=true \
      -Dtest=true \
      -Dvideotestsrc=true \
      -Dvolume=true \
    && make && make test'
